# Generated by Django 2.2.12 on 2020-06-28 17:11

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generic',
            new_name='Data',
        ),
    ]
